export default [
  {
    name: 'STOPLIGHT',
    fullName: 'STOPLIGHT',
    rule: 'STOPLIGHT_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
    emoji: '🚦',
    countdown: true,
  },
  {
    name: 'MATH_BATTLE',
    fullName: 'MATH BATTLE',
    rule: 'MATH_BATTLE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '🤓',
    countdown: true,
  },
  {
    name: 'POP_THE_BALLOON',
    fullName: 'POP THE BALLOON',
    rule: 'POP_THE_BALLOON_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
    emoji: '🎈',
    countdown: true,
  },
  {
    name: 'RED_GREEN_BLUE',
    fullName: 'RED GREEN BLUE',
    rule: 'RED_GREEN_BLUE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '🎨',
    countdown: true,
  },
  {
    name: 'WHACK_A_MOLE',
    fullName: 'WHACK A MOLE',
    rule: 'WHACK_A_MOLE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '🐭',
    countdown: true,
  },
  {
    name: 'NUMBER',
    fullName: 'NUMBER',
    rule: 'NUMBER_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
    emoji: '⚡️',
    countdown: true,
  },
  {
    name: 'IDENTICAL',
    fullName: 'IDENTICAL',
    rule: 'IDENTICAL_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '🍻',
    countdown: true,
  },
  {
    name: 'LUCKY',
    fullName: 'LUCKY',
    rule: 'LUCKY_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '💰',
    countdown: false,
  },
  {
    name: 'RIGHT_ON',
    fullName: 'RIGHT ON',
    rule: 'RIGHT_ON_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
    emoji: '⏱',
    countdown: false,
  },
  {
    name: 'REAL_COLOR',
    fullName: 'REAL COLOR',
    rule: 'REAL_COLOR_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
    emoji: '🖌',
    countdown: true,
  },
  {
    name: 'MEMORY',
    fullName: 'MEMORY',
    rule: 'MEMORY_RULE',
    winner: 'SMALLEST',
    scoreType: 'TRIES',
    emoji: '👀',
    countdown: false,
  },
];
