export default [
  {
    name: 'STOPLIGHT',
    fullName: 'STOPLIGHT',
    rule: 'Press the GO button as soon as the light turns green!',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'MATH_BATTLE',
    fullName: 'MATH BATTLE',
    rule: 'Press on the multiplication with the bigger result!',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'POP_THE_BALLOON',
    fullName: 'POP THE BALLOON',
    rule: 'Press 50 times on the balloon as quickly as possible to pop it!',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'RED_GREEN_BLUE',
    fullName: 'RED GREEN BLUE',
    rule: 'Press on the color that’s on the board as fast as possible!',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'WHACK_A_MOLE',
    fullName: 'WHACK A MOLE',
    rule: 'Press on the circles as soon as they turn yellow!',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'NUMBER',
    fullName: 'NUMBER',
    rule: 'Press on the numbers from 1 to 9 as quickly as you can!',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'IDENTICAL',
    fullName: 'IDENTICAL',
    rule: 'Is the current emoji the same as the previous one?',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'LUCKY',
    fullName: 'LUCKY',
    rule: 'Turn over as many cells as possible without flipping the ☠!',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'RIGHT_ON',
    fullName: 'RIGHT ON',
    rule: 'Stop the timer on 3 seconds, 3 times in a row!',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'REAL_COLOR',
    fullName: 'REAL COLOR',
    rule: 'Does the meaning of the word match the color?',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
];
