export default [
  {
    name: 'STOPLIGHT',
    fullName: 'STOPLIGHT',
    rule: 'STOPLIGHT_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'MATH_BATTLE',
    fullName: 'MATH BATTLE',
    rule: 'MATH_BATTLE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'POP_THE_BALLOON',
    fullName: 'POP THE BALLOON',
    rule: 'POP_THE_BALLOON_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'RED_GREEN_BLUE',
    fullName: 'RED GREEN BLUE',
    rule: 'RED_GREEN_BLUE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'WHACK_A_MOLE',
    fullName: 'WHACK A MOLE',
    rule: 'WHACK_A_MOLE_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'NUMBER',
    fullName: 'NUMBER',
    rule: 'NUMBER_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'IDENTICAL',
    fullName: 'IDENTICAL',
    rule: 'IDENTICAL_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'LUCKY',
    fullName: 'LUCKY',
    rule: 'LUCKY_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
  {
    name: 'RIGHT_ON',
    fullName: 'RIGHT ON',
    rule: 'RIGHT_ON_RULE',
    winner: 'SMALLEST',
    scoreType: 'DATE',
  },
  {
    name: 'REAL_COLOR',
    fullName: 'REAL COLOR',
    rule: 'REAL_COLOR_RULE',
    winner: 'GREATEST',
    scoreType: 'NUMBER',
  },
];
